# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 22:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('userGroup', '0004_auto_20170913_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('checked', models.ManyToManyField(to='userGroup.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='options',
            field=models.ManyToManyField(to='dashBoard.option'),
        ),
        migrations.AddField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(to='dashBoard.offer'),
        ),
    ]
