# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('userGroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(to='userGroup.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='DashUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('active', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=300)),
                ('code', models.CharField(default='0', max_length=10)),
                ('unit', models.CharField(max_length=50)),
                ('gen_message', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry_in', models.CharField(blank=True, default=10, max_length=10)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('alerted', models.ManyToManyField(blank=True, related_name='alerted', to='userGroup.Profile')),
                ('answers', models.ManyToManyField(blank=True, to='dashBoard.Answer')),
                ('selected', models.ManyToManyField(blank=True, related_name='selected', to='userGroup.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Offer'),
        ),
    ]
