# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='options',
            field=models.ManyToManyField(blank=True, to='dashBoard.option'),
        ),
        migrations.AlterField(
            model_name='option',
            name='checked',
            field=models.ManyToManyField(blank=True, to='userGroup.Profile'),
        ),
    ]
