# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0002_auto_20170914_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='option',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='options',
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Offer'),
        ),
        migrations.DeleteModel(
            name='option',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashBoard.DashUser'),
        ),
        migrations.AddField(
            model_name='offer',
            name='answers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Answer'),
        ),
    ]
