# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('dashBoard', '0006_auto_20170915_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashuser',
            name='reports',
            field=models.ManyToManyField(to='reports.report'),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Offer'),
        ),
    ]
