# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0009_auto_20170917_1924'),
        ('reports', '0003_auto_20170915_1246'),
        ('dashBoard', '0010_auto_20170915_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reports',
            field=models.ManyToManyField(to='reports.report'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ManyToManyField(to='userGroup.Profile'),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Offer'),
        ),
    ]
