# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0011_auto_20170917_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='message',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Offer'),
        ),
    ]
