# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0015_auto_20170919_2047'),
        ('dashBoard', '0017_auto_20170918_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='alerted',
            field=models.ManyToManyField(blank=True, related_name='alerted', to='userGroup.Profile'),
        ),
        migrations.AddField(
            model_name='offer',
            name='selected',
            field=models.ManyToManyField(blank=True, related_name='selected', to='userGroup.Profile'),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Offer'),
        ),
    ]
