# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0019_auto_20170919_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expiry_in',
            field=models.CharField(blank=True, default=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Offer'),
        ),
    ]
