# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0020_auto_20170919_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
