# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0029_auto_20170922_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='gen_message',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='offers',
            field=models.ManyToManyField(blank=True, to='dashBoard.Offer'),
        ),
    ]
