# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='answers',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
