# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='answers',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
