# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('msg', models.CharField(max_length=500)),
                ('resp_msg', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('api_resp', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
