# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=60)),
                ('last', models.CharField(max_length=60)),
                ('nr', models.CharField(max_length=30)),
                ('gps_lat', models.CharField(blank=True, max_length=10)),
                ('gps_long', models.CharField(blank=True, max_length=10)),
                ('village', models.CharField(blank=True, max_length=60)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('region', models.CharField(blank=True, max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
