# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0002_profile_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
