# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0003_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.CharField(default='eng', max_length=5),
        ),
    ]
