# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0004_auto_20170913_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profiles', models.ManyToManyField(to='userGroup.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='address',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='contact',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='userGroup.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='district',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='region',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='village',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
