# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0005_auto_20170914_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrests',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='userGroup.Profile'),
        ),
    ]
