# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0006_auto_20170914_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intrests',
            new_name='interests',
        ),
    ]
