# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0009_auto_20170917_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(blank=True, to='userGroup.Interest'),
        ),
    ]
