# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0014_auto_20170918_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(blank=True, to='userGroup.Interest'),
        ),
    ]
