# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0016_auto_20170919_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(blank=True, to='userGroup.Interest'),
        ),
    ]
