# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0020_auto_20170920_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userGroup.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(blank=True, to='userGroup.Interest'),
        ),
    ]
