# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0023_auto_20170920_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.RemoveField(
            model_name='group',
            name='contact',
        ),
        migrations.AddField(
            model_name='group',
            name='contact',
            field=models.ManyToManyField(blank=True, to='userGroup.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='district',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='region',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(blank=True, to='userGroup.Interest'),
        ),
    ]
