# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0024_auto_20170920_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interest',
            new_name='interests',
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='userGroup.Interest'),
        ),
    ]
