# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0026_auto_20170922_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='userGroup.Interest'),
        ),
    ]
